/* ============================================================
   章节分类数据 — IG (CIE 0620) 19 章 / AP (教程原稿) 13 章
   ------------------------------------------------------------
   CHAPTER_OF : 每个模型文件 -> { ig: IG 章号, ap: AP 章号 }
                0 表示大纲/书本之外的「其他」类
   CHAPTERS   : 两种模式下的章节按钮定义（label 为按钮文字，
                full 为完整章名，count 为模型数量）
   新增模型时只需在 CHAPTER_OF 补一行即可。
   ============================================================ */

window.CHAPTER_OF = {
  "Collision.html": { ig: 9, ap: 9 },
  "Copper plating.html": { ig: 7, ap: 12 },
  "Extraction of Al .html": { ig: 14, ap: 12 },
  "Extraction of al.html": { ig: 14, ap: 12 },
  "Haber process 公开课模型.html": { ig: 10, ap: 10 },
  "Halogen displacement.html": { ig: 12, ap: 4 },
  "Hydrogen fuel cell.html": { ig: 8, ap: 12 },
  "Mass spectrum.html": { ig: 2, ap: 5 },
  "mass_spec_model.html": { ig: 2, ap: 5 },
  "PH与食欲.html": { ig: 11, ap: 11 },
  "Titration 2 .html": { ig: 11, ap: 11 },
  "铵盐与碱.html": { ig: 11, ap: 11 },
  "沉淀的产生.html": { ig: 11, ap: 4 },
  "沉淀盐的产生.html": { ig: 11, ap: 4 },
  "触电模拟.html": { ig: 0, ap: 0 },
  "滴定.html": { ig: 11, ap: 11 },
  "电池闭合回路的产生.html": { ig: 7, ap: 12 },
  "电镀电极材料.html": { ig: 7, ap: 12 },
  "电镀金模型.html": { ig: 7, ap: 12 },
  "电解不同溶液.html": { ig: 7, ap: 12 },
  "电解池的微观构成.html": { ig: 7, ap: 12 },
  "电解氯化铜.html": { ig: 7, ap: 12 },
  "电解水.html": { ig: 7, ap: 12 },
  "镀铜.html": { ig: 7, ap: 12 },
  "反应平衡.html": { ig: 10, ap: 10 },
  "高炉炼铁.html": { ig: 14, ap: 0 },
  "公开课模型.html": { ig: 10, ap: 10 },
  "合金的延展性.html": { ig: 14, ap: 3 },
  "碱性的中和.html": { ig: 11, ap: 11 },
  "金属displacement reaction.html": { ig: 13, ap: 4 },
  "金属与酸.html": { ig: 11, ap: 11 },
  "难溶盐的制备.html": { ig: 11, ap: 4 },
  "强酸的腐蚀性.html": { ig: 11, ap: 11 },
  "强酸弱酸实验.html": { ig: 11, ap: 11 },
  "强酸与弱酸的水解.html": { ig: 11, ap: 11 },
  "酸与金属.html": { ig: 11, ap: 11 },
  "碳酸根.html": { ig: 11, ap: 11 },
  "盐的制备1.html": { ig: 11, ap: 4 },
  "制备可溶性盐.html": { ig: 11, ap: 4 },
  "治疗sting.html": { ig: 11, ap: 11 },
  "delta H c.html": { ig: 8, ap: 8 },
  "Endo and exo .html": { ig: 8, ap: 8 },
  "公开课simple calorimeter.html": { ig: 8, ap: 8 },
  "改进量热计.html": { ig: 8, ap: 8 },
  "fractional distillation.html": { ig: 16, ap: 13 },
  "Ethane cracking.html": { ig: 16, ap: 0 },
  "Substitution reaction.html": { ig: 16, ap: 0 },
  "Addtion reaction of ethene.html": { ig: 16, ap: 0 },
  "Cracking.html": { ig: 16, ap: 0 },
  "Fermentation.html": { ig: 16, ap: 0 },
  "oxidation of alcohol.html": { ig: 16, ap: 0 },
  "alcohol change .html": { ig: 16, ap: 0 },
  "Polyamide.html": { ig: 17, ap: 0 },
  "Polyester.html": { ig: 17, ap: 0 },
  "Protein.html": { ig: 17, ap: 0 },
  "esterification.html": { ig: 16, ap: 0 },
  "Identify amino acid.html": { ig: 18, ap: 13 },
  "identify substance.html": { ig: 18, ap: 13 },
  "橙汁分析.html": { ig: 18, ap: 13 },
  "酸性腐蚀.html": { ig: 11, ap: 11 },
  "PHvalue.html": { ig: 11, ap: 11 },
  "强酸与弱酸的解离.html": { ig: 11, ap: 11 },
  "02-reaction-profile.html": { ig: 8, ap: 8 },
  "03-energy-level-builder.html": { ig: 8, ap: 8 },
  "04-bond-energy-flow.html": { ig: 8, ap: 8 },
  "05-bond-energy-calculator.html": { ig: 8, ap: 8 },
  "06-calorimetry-fuel.html": { ig: 8, ap: 8 },
  "CO2对比石墨-熔点模型.html": { ig: 3, ap: 3 },
  "Ch3 L1-3 气液平衡·真空里自己涨起来的气压.html": { ig: 1, ap: 3 },
  "Ch3 L1-3 蒸汽压与沸点·顶得开才沸腾.html": { ig: 1, ap: 3 },
  "Conductivity_Ionic_vs_Metallic.html": { ig: 3, ap: 3 },
  "Dipole极性模型.html": { ig: 3, ap: 2 },
  "Intermolecular_Forces.html": { ig: 3, ap: 3 },
  "PES光电子能谱模型.html": { ig: 2, ap: 1 },
  "Sigma_Pi_Hybridization.html": { ig: 3, ap: 2 },
  "U-235裂变模型.html": { ig: 0, ap: 0 },
  "VSEPR模型.html": { ig: 3, ap: 2 },
  "diffusion-simulator.html": { ig: 1, ap: 3 },
  "matter-states-cushion.html": { ig: 1, ap: 3 },
  "pipe-flow.html": { ig: 0, ap: 0 },
  "states-of-matter-interactive.html": { ig: 1, ap: 3 },
  "亚层轨道电离能差异模型.html": { ig: 2, ap: 1 },
  "亚层轨道电离能差异模型_无亚层图.html": { ig: 2, ap: 1 },
  "元素分析仪·元素种类与质量百分比.html": { ig: 5, ap: 5 },
  "分子间作用力·形成机制三场景.html": { ig: 3, ap: 3 },
  "化学键形成过程 (AP).html": { ig: 3, ap: 2 },
  "化学键形成过程 (IG).html": { ig: 3, ap: 2 },
  "化学键的断裂与重组.html": { ig: 3, ap: 2 },
  "原子同位素质谱与丰度偏转模拟器.html": { ig: 2, ap: 5 },
  "原子离子半径趋势-热力图.html": { ig: 12, ap: 1 },
  "原子离子半径趋势-热力图_无亚层图.html": { ig: 12, ap: 1 },
  "合金的两种固溶模型.html": { ig: 14, ap: 3 },
  "扩散模型-微粒视角.html": { ig: 1, ap: 3 },
  "杂化轨道与σπ键-3D模型.html": { ig: 3, ap: 2 },
  "焦糖化·微观机理模型.html": { ig: 0, ap: 0 },
  "焰色反应微观模型.html": { ig: 19, ap: 1 },
  "熔点对比·任选两物质.html": { ig: 3, ap: 3 },
  "物质三态变化.html": { ig: 1, ap: 3 },
  "电子轨道排布模型.html": { ig: 2, ap: 1 },
  "电离能.html": { ig: 2, ap: 1 },
  "相对原子质量·天平与标尺 (AP).html": { ig: 2, ap: 5 },
  "相对原子质量·天平与标尺 (IG).html": { ig: 2, ap: 5 },
  "离子方程式·微粒交互模型.html": { ig: 4, ap: 4 },
  "离子晶体脆性模型.html": { ig: 3, ap: 3 },
  "金刚石对比SiO2-熔点模型.html": { ig: 3, ap: 3 },
  "金刚石对比石墨-熔点模型.html": { ig: 3, ap: 3 },
  "金属的延展性.html": { ig: 3, ap: 3 },
  "键长与势能曲线·不同原子对.html": { ig: 3, ap: 2 },
  "氧化还原·电子得失.html": { ig: 6, ap: 4 }
};

window.CHAPTERS = {
  alig: [
    { n: 1, key: "ig1", label: "Ch 1 · States of Matter", full: "第1章 States of matter 物质的三态", count: 7 },
    { n: 2, key: "ig2", label: "Ch 2 · Atoms & Elements", full: "第2章 Atoms and elements 原子与元素", count: 10 },
    { n: 3, key: "ig3", label: "Ch 3 · Atoms Combining", full: "第3章 Atoms combining 原子结合（化学键）", count: 17 },
    { n: 4, key: "ig4", label: "Ch 4 · Reacting Masses", full: "第4章 Reacting masses, and chemical equations 反应质量与化学方程式", count: 1 },
    { n: 5, key: "ig5", label: "Ch 5 · Using Moles", full: "第5章 Using moles 摩尔计算", count: 1 },
    { n: 6, key: "ig6", label: "Ch 6 · Redox Reactions", full: "第6章 Redox reactions 氧化还原反应", count: 1 },
    { n: 7, key: "ig7", label: "Ch 7 · Electricity & Chem Change", full: "第7章 Electricity and chemical change 电与化学变化（电解）", count: 9 },
    { n: 8, key: "ig8", label: "Ch 8 · Energy Changes", full: "第8章 Energy changes in reactions 反应中的能量变化", count: 10 },
    { n: 9, key: "ig9", label: "Ch 9 · Rate of Reaction", full: "第9章 The rate of reaction 反应速率", count: 1 },
    { n: 10, key: "ig10", label: "Ch 10 · Equilibrium", full: "第10章 Reversible reactions and equilibrium 可逆反应与平衡", count: 3 },
    { n: 11, key: "ig11", label: "Ch 11 · Acids, Bases & Salts", full: "第11章 Acids, bases and salts 酸、碱与盐", count: 20 },
    { n: 12, key: "ig12", label: "Ch 12 · The Periodic Table", full: "第12章 The Periodic Table 元素周期表", count: 3 },
    { n: 13, key: "ig13", label: "Ch 13 · Behaviour of Metals", full: "第13章 The behaviour of metals 金属的行为（活动性）", count: 1 },
    { n: 14, key: "ig14", label: "Ch 14 · Extracting Metals", full: "第14章 Extracting and using metals 金属的提炼与使用", count: 5 },
    { n: 15, key: "ig15", label: "Ch 15 · Environment", full: "第15章 Chemistry of the environment 环境化学", count: 0 },
    { n: 16, key: "ig16", label: "Ch 16 · Organic Chemistry", full: "第16章 Organic chemistry 有机化学", count: 9 },
    { n: 17, key: "ig17", label: "Ch 17 · Polymers", full: "第17章 Polymers 聚合物", count: 3 },
    { n: 18, key: "ig18", label: "Ch 18 · Separation & Purification", full: "第18章 Separation and purification 分离与提纯", count: 3 },
    { n: 19, key: "ig19", label: "Ch 19 · Experiments & Tests", full: "第19章 Experiments and tests in the lab 实验与检验", count: 1 },
    { n: 0, key: "ig0", label: "其他 · Other", full: "大纲之外 Other / Beyond the IGCSE syllabus", count: 4 }
  ],
  ap: [
    { n: 1, key: "ap1", label: "第1章 · 原子结构", full: "第一章 原子结构与元素周期表 Atomic Structure and the Periodic Table", count: 8 },
    { n: 2, key: "ap2", label: "第2章 · 化学键", full: "第二章 原子间的互动——化学键 Interactions Between Atoms – Chemical Bonding", count: 8 },
    { n: 3, key: "ap3", label: "第3章 · 物理性质", full: "第三章 由微观到宏观——物理性质 From Micro to Macro – Physical Properties", count: 18 },
    { n: 4, key: "ap4", label: "第4章 · 化学反应", full: "第四章 化学反应 Chemical Reactions", count: 9 },
    { n: 5, key: "ap5", label: "第5章 · 化学计量", full: "第五章 化学中的定量分析——化学计量学 Stoichiometry", count: 6 },
    { n: 6, key: "ap6", label: "第6章 · 气体", full: "第六章 “自由”的粒子——气体 Gases", count: 0 },
    { n: 7, key: "ap7", label: "第7章 · 溶液", full: "第七章 均匀混合物——溶液 Solutions", count: 0 },
    { n: 8, key: "ap8", label: "第8章 · 热力学", full: "第八章 化学中的能量变化——热力学 Thermodynamics", count: 9 },
    { n: 9, key: "ap9", label: "第9章 · 动力学", full: "第九章 化学反应的快慢——动力学 Kinetics", count: 1 },
    { n: 10, key: "ap10", label: "第10章 · 化学平衡", full: "第十章 宇宙的“偏爱”——化学平衡 Equilibrium", count: 3 },
    { n: 11, key: "ap11", label: "第11章 · 酸与碱", full: "第十一章 酸与碱 Acids and Bases", count: 15 },
    { n: 12, key: "ap12", label: "第12章 · 电化学", full: "第十二章 化学能与电能——电化学 Electrochemistry", count: 12 },
    { n: 13, key: "ap13", label: "第13章 · 实验操作", full: "第十三章 实验操作 Practical", count: 4 },
    { n: 0, key: "ap0", label: "综合 · 其他", full: "本书未覆盖的主题 Topics not covered in this AP textbook", count: 16 }
  ]
};
